#https://github.com/vaxilu/x-ui
name: build_baota_clear.yaml

# 需要填写变量 ORIGINAL_OWNER ORIGINAL_REPOSITORY UPSTREAM_BRANCH MY_BRANCH
# 需要创建环境变量 MYGITHUB_TOKEN MYGITHUB_USERNAME
env:
  ORIGINAL_OWNER: vaxilu
  ORIGINAL_REPOSITORY: x-ui
  MYORIGINAL_REPOSITORY: x-ui
  UPSTREAM_BRANCH: main
  MY_BRANCH: main

on:
  workflow_dispatch:
  repository_dispatch:
    types: [1]
  # schedule:
  #   - cron: '0 */4 * * *'

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
    steps:
    - name: set env
      run: |
          echo "ORIGINAL_OWNER=${{ env.ORIGINAL_OWNER }}" >> $GITHUB_ENV
          echo "ORIGINAL_REPOSITORY=${{ env.ORIGINAL_REPOSITORY }}" >> $GITHUB_ENV
          echo "MYORIGINAL_REPOSITORY=${{ env.MYORIGINAL_REPOSITORY }}" >> $GITHUB_ENV
          echo "UPSTREAM_BRANCH=${{ env.UPSTREAM_BRANCH }}" >> $GITHUB_ENV
          echo "MY_BRANCH=${{ env.MY_BRANCH }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.MYGITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "repository_owner=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "repository=${{ github.repository }}" >> $GITHUB_ENV
          echo "MYPASSWD=${{ secrets.MYPASSWD }}" >> $GITHUB_ENV
          echo "MYSALT=${{ secrets.MYSALT }}" >> $GITHUB_ENV

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 安装依赖 Install dependencies
      run: sudo apt-get install jq curl

    - name: key
      run: |
          wget -O ../key.sh https://git.blog.jiangqing.xyz/shell/linux/actions/key.sh
          bash ../key.sh

    - name: 登录dockerhub
      run: |
          wget -O ../clone_reset.sh https://git.blog.jiangqing.xyz/shell/linux/actions/clone_reset.sh
          bash ../clone_reset.sh
    
    - name: 克隆脚本仓库 (Clone and Reset)
      run: |
          wget -O ../clone_reset.sh https://git.blog.jiangqing.xyz/shell/linux/actions/clone_reset.sh
          bash ../clone_reset.sh
    
     - name: build
      run: |
          wget -O ../clone_reset.sh https://git.blog.jiangqing.xyz/shell/linux/actions/clone_reset.sh
          bash ../clone_reset.sh
        
     - name: push
      run: |
          wget -O ../clone_reset.sh https://git.blog.jiangqing.xyz/shell/linux/actions/clone_reset.sh
          bash ../clone_reset.sh